version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/pull_image.sh
      timeout: 300
      runas: ec2-user  # Changed from root to ec2-user
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: ec2-user  # Changed from root to ec2-user