version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/pull_image.sh  # Updated to match buildspec.yml
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh  # Updated to match buildspec.yml
      timeout: 300
      runas: root