version: 0.0
os: linux
files:
  - source: /  # Deploys all files from the artifact root (artifacts/)
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: artifacts/scripts/pull_image.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: artifacts/scripts/start_service.sh
      timeout: 300
      runas: root