version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/pull_image.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root