version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t shark-website .
      - docker tag shark-website:latest $ECR_REPO:$ENVIRONMENT

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO:$ENVIRONMENT
      - echo Build completed successfully
      - echo Preparing deployment artifacts...
      - mkdir -p artifacts/scripts
      - cp scripts/pull_image.sh artifacts/scripts/
      - cp scripts/start_service.sh artifacts/scripts/
      - cp appspec.yml artifacts/

artifacts:
  files:
    - artifacts/**  # Ensures all deployment files are included
  discard-paths: no
